name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      uses: pmorelli92/github-container-registry-build-push@2.1.0
      with:
        github-push-secret: ${DEPLOY_SECRET}
        docker-image-name: maybeec/pyspelling-any
        build-only: true
