name: Docker Image Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      uses: pmorelli92/github-container-registry-build-push@2.1.0
      with:
        # Token such as GITHUB_TOKEN that has `write:packages` scope to authenticate against GCHR.
        github-push-secret: ${DEPLOY_SECRET}
        docker-image-name: maybeec/pyspelling-any
        docker-image-tag: $GITHUB_REF_NAME
